### ISSUE TITLE
 Error fetching entities for both entities and sensors

### ISSUE THREAD

**Issue by SilverNodashi** [grafolean/grafolean#37]
- I have an Ubuntu 20 server setup with grafolean as per the instructions, on 192.168.100.157:

- A MikroTik on 192.168.100.3 and PFSense firewall on 192.168.100.1. Both are setup to send their Netflow traffic to 192.168.100.157. 

Now, when I goto entities, or sensors, I get an " Error fetching entities" erro.
![image](https://github.com/grafolean/grafolean/assets/17824870/10c716d9-3cb6-42e2-a096-c73a13c11a55)

![image](https://github.com/grafolean/grafolean/assets/17824870/1638d1d9-e518-499e-8448-62ff5ed1426d)

Any suggestions for this?

**Comment by grafolean** [comment]
Did you manage to solve #36? If not, that could be a reason for this problem. Otherwise, can you maybe post there so that we know what went wrong?

If #36 was solved: judging by the logs of netflow agent (bot), it encounters response `500` when trying to reach Grafolean, so it seems the problem is on the Grafolean side. Can you maybe post the corresponding logs of `grafolean` container (`docker logs -f grafolean`)?

**Comment by grafolean** [comment]
Closing this as stale, feel free to reopen if it still happens.
